# =============================================================================
# General Project Configuration (Unified)
# =============================================================================

[general]
project_name = "vus-life"
version = "0.1.0"

# =============================================================================
# Models, Annotation Types
# =============================================================================

[models]

embedding_models = [
"all-mpnet-base-v2", 
"MedEmbed-large-v0.1",
"google-embedding"
]

[annotation_methods]
method_names = ["vep"]

[genes]
gene_names = [
    "ATM", 
    "PALB2",
    "FBN1",
    "BRCA1",
    "BRCA2",
    ]

# =============================================================================
# Paths (Template Variables)
# =============================================================================


[paths.user]
base_dir = "data_user"

[paths.user.training_results]
training_dimension_plots_dir = "training_embedding_results/embedding_plot_dir"
training_coordinates_dir = "training_embedding_results/coordinates"
training_metadata_dir = "training_embedding_results/metadata"

[paths.user.user_query]
user_query_inputs_dir = "user_query/inputs"
user_query_results_dir = "user_query/retrieval_results"
user_query_processed_dir = "user_query/processed_results"


# [paths.evaluation.results]
# # Results structure

# result_embedding_dir = "embedding"
# result_accuracy_dir = "accuracy"
# result_prediction_dir = "prediction"
# result_distance_ratio_dir = "distance_ratio"

# deduction_models_dir = "{results_dir}/{model}/dimension_deduction_models"
# embedding_results_dir = "{results_dir}/{model}/embedding_plot_dir"
# accuracy_results_dir = "{results_dir}/{model}/accuracy_dir"
# comparative_results_dir = "{results_dir}/comparative_results"

[paths.others]
log_base_dir = "logs"




